# Generated by Django 2.0.2 on 2019-03-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0002_auto_20190307_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symcomponent',
            name='nagative_sequence',
            field=models.BinaryField(blank=True, null=True, verbose_name='Negative sequence waveform'),
        ),
        migrations.AlterField(
            model_name='symcomponent',
            name='positive_sequence',
            field=models.BinaryField(blank=True, null=True, verbose_name='Positive sequence waveform'),
        ),
        migrations.AlterField(
            model_name='symcomponent',
            name='zero_sequence',
            field=models.BinaryField(blank=True, null=True, verbose_name='Zero sequence waveform'),
        ),
        migrations.AlterField(
            model_name='uphase',
            name='complex_signal',
            field=models.BinaryField(blank=True, null=True, verbose_name='Complex signal'),
        ),
        migrations.AlterField(
            model_name='uprocessed',
            name='env',
            field=models.BinaryField(blank=True, null=True, verbose_name='Envelope'),
        ),
        migrations.AlterField(
            model_name='uprocessed',
            name='env_spec',
            field=models.BinaryField(blank=True, null=True, verbose_name='Spectrum of Envelope'),
        ),
        migrations.AlterField(
            model_name='uprocessed',
            name='spec',
            field=models.BinaryField(blank=True, null=True, verbose_name='Spectrum'),
        ),
        migrations.AlterField(
            model_name='vphase',
            name='complex_signal',
            field=models.BinaryField(blank=True, null=True, verbose_name='Complex signal'),
        ),
        migrations.AlterField(
            model_name='vprocessed',
            name='env',
            field=models.BinaryField(blank=True, null=True, verbose_name='Envelope'),
        ),
        migrations.AlterField(
            model_name='vprocessed',
            name='env_spec',
            field=models.BinaryField(blank=True, null=True, verbose_name='Spectrum of Envelope'),
        ),
        migrations.AlterField(
            model_name='vprocessed',
            name='spec',
            field=models.BinaryField(blank=True, null=True, verbose_name='Spectrum'),
        ),
        migrations.AlterField(
            model_name='wphase',
            name='complex_signal',
            field=models.BinaryField(blank=True, null=True, verbose_name='Complex signal'),
        ),
        migrations.AlterField(
            model_name='wprocessed',
            name='env',
            field=models.BinaryField(blank=True, null=True, verbose_name='Envelope'),
        ),
        migrations.AlterField(
            model_name='wprocessed',
            name='env_spec',
            field=models.BinaryField(blank=True, null=True, verbose_name='Spectrum of Envelope'),
        ),
        migrations.AlterField(
            model_name='wprocessed',
            name='spec',
            field=models.BinaryField(blank=True, null=True, verbose_name='Spectrum'),
        ),
    ]
