# Generated by Django 2.0.2 on 2019-03-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0003_auto_20190307_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='ufeature',
            name='max_current',
            field=models.FloatField(default=0, verbose_name='Maximum current value'),
        ),
        migrations.AddField(
            model_name='ufeature',
            name='min_current',
            field=models.FloatField(default=0, verbose_name='Minimum current value'),
        ),
        migrations.AddField(
            model_name='vfeature',
            name='max_current',
            field=models.FloatField(default=0, verbose_name='Maximum current value'),
        ),
        migrations.AddField(
            model_name='vfeature',
            name='min_current',
            field=models.FloatField(default=0, verbose_name='Minimum current value'),
        ),
        migrations.AddField(
            model_name='wfeature',
            name='max_current',
            field=models.FloatField(default=0, verbose_name='Maximum current value'),
        ),
        migrations.AddField(
            model_name='wfeature',
            name='min_current',
            field=models.FloatField(default=0, verbose_name='Minimum current value'),
        ),
    ]
