# Generated by Django 2.0.2 on 2019-03-10 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0004_auto_20190308_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ufeature',
            name='fbpfi',
        ),
        migrations.RemoveField(
            model_name='ufeature',
            name='fbpfo',
        ),
        migrations.RemoveField(
            model_name='ufeature',
            name='fbrb',
        ),
        migrations.RemoveField(
            model_name='ufeature',
            name='fbsf',
        ),
        migrations.RemoveField(
            model_name='vfeature',
            name='fbpfi',
        ),
        migrations.RemoveField(
            model_name='vfeature',
            name='fbpfo',
        ),
        migrations.RemoveField(
            model_name='vfeature',
            name='fbrb',
        ),
        migrations.RemoveField(
            model_name='vfeature',
            name='fbsf',
        ),
        migrations.RemoveField(
            model_name='wfeature',
            name='fbpfi',
        ),
        migrations.RemoveField(
            model_name='wfeature',
            name='fbpfo',
        ),
        migrations.RemoveField(
            model_name='wfeature',
            name='fbrb',
        ),
        migrations.RemoveField(
            model_name='wfeature',
            name='fbsf',
        ),
    ]
