# Generated by Django 2.0.2 on 2019-03-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0005_auto_20190310_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uphase',
            name='complex_signal',
        ),
        migrations.RemoveField(
            model_name='vphase',
            name='complex_signal',
        ),
        migrations.RemoveField(
            model_name='wphase',
            name='complex_signal',
        ),
        migrations.AddField(
            model_name='uphase',
            name='estimated_parameter',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Estimated parameter'),
        ),
        migrations.AddField(
            model_name='vphase',
            name='estimated_parameter',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Estimated parameter'),
        ),
        migrations.AddField(
            model_name='wphase',
            name='estimated_parameter',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Estimated parameter'),
        ),
    ]
