# Generated by Django 2.0.2 on 2019-03-18 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0006_auto_20190311_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uprocessed',
            name='signal_pack',
        ),
        migrations.RemoveField(
            model_name='vprocessed',
            name='signal_pack',
        ),
        migrations.RemoveField(
            model_name='wprocessed',
            name='signal_pack',
        ),
        migrations.RemoveField(
            model_name='symcomponent',
            name='nagative_sequence',
        ),
        migrations.RemoveField(
            model_name='symcomponent',
            name='positive_sequence',
        ),
        migrations.RemoveField(
            model_name='symcomponent',
            name='zero_sequence',
        ),
        migrations.RemoveField(
            model_name='uphase',
            name='estimated_parameter',
        ),
        migrations.RemoveField(
            model_name='vphase',
            name='estimated_parameter',
        ),
        migrations.RemoveField(
            model_name='wphase',
            name='estimated_parameter',
        ),
        migrations.AddField(
            model_name='uphase',
            name='amplitude',
            field=models.FloatField(default=0, verbose_name='AMP'),
        ),
        migrations.AddField(
            model_name='uphase',
            name='frequency',
            field=models.FloatField(default=0, verbose_name='PSF'),
        ),
        migrations.AddField(
            model_name='uphase',
            name='initial_phase',
            field=models.FloatField(default=0, verbose_name='IPA'),
        ),
        migrations.AddField(
            model_name='vphase',
            name='amplitude',
            field=models.FloatField(default=0, verbose_name='AMP'),
        ),
        migrations.AddField(
            model_name='vphase',
            name='frequency',
            field=models.FloatField(default=0, verbose_name='PSF'),
        ),
        migrations.AddField(
            model_name='vphase',
            name='initial_phase',
            field=models.FloatField(default=0, verbose_name='IPA'),
        ),
        migrations.AddField(
            model_name='wphase',
            name='amplitude',
            field=models.FloatField(default=0, verbose_name='AMP'),
        ),
        migrations.AddField(
            model_name='wphase',
            name='frequency',
            field=models.FloatField(default=0, verbose_name='PSF'),
        ),
        migrations.AddField(
            model_name='wphase',
            name='initial_phase',
            field=models.FloatField(default=0, verbose_name='IPA'),
        ),
        migrations.AlterField(
            model_name='bearing',
            name='motor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bearings', to='motors.Motor'),
        ),
        migrations.AlterField(
            model_name='bearing',
            name='tags',
            field=models.ManyToManyField(blank=True, to='motors.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='currentsignalpack',
            name='motor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='motors.Motor'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='tags',
            field=models.ManyToManyField(blank=True, to='motors.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='rotor',
            name='motor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotors', to='motors.Motor'),
        ),
        migrations.AlterField(
            model_name='rotor',
            name='tags',
            field=models.ManyToManyField(blank=True, to='motors.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='stator',
            name='motor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stators', to='motors.Motor'),
        ),
        migrations.AlterField(
            model_name='stator',
            name='tags',
            field=models.ManyToManyField(blank=True, to='motors.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Uprocessed',
        ),
        migrations.DeleteModel(
            name='Vprocessed',
        ),
        migrations.DeleteModel(
            name='Wprocessed',
        ),
    ]
