# Generated by Django 2.0.2 on 2019-03-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0007_auto_20190318_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ufeature',
            name='harmonics',
            field=models.BinaryField(verbose_name='1st-20th harmonic energy'),
        ),
        migrations.AlterField(
            model_name='vfeature',
            name='harmonics',
            field=models.BinaryField(verbose_name='1st-20th harmonic energy'),
        ),
        migrations.AlterField(
            model_name='wfeature',
            name='harmonics',
            field=models.BinaryField(verbose_name='1st-20th harmonic energy'),
        ),
    ]
