# Generated by Django 2.0.2 on 2019-03-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0009_auto_20190318_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='bearing',
            name='health_indicator',
            field=models.FloatField(default=85, verbose_name='Value of Health Indicator'),
        ),
        migrations.AddField(
            model_name='motor',
            name='health_indicator',
            field=models.FloatField(default=85, verbose_name='Value of Health Indicator'),
        ),
        migrations.AddField(
            model_name='rotor',
            name='health_indicator',
            field=models.FloatField(default=85, verbose_name='Value of Health Indicator'),
        ),
        migrations.AddField(
            model_name='stator',
            name='health_indicator',
            field=models.FloatField(default=85, verbose_name='Value of Health Indicator'),
        ),
    ]
