# Generated by Django 2.0.2 on 2019-03-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0010_auto_20190322_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='bearing',
            name='equip_type',
            field=models.SmallIntegerField(choices=[(0, 'Motor'), (1, 'Bearing'), (2, 'Rotor'), (3, 'Stator')], default=1, verbose_name='Equipment type'),
        ),
        migrations.AddField(
            model_name='motor',
            name='equip_type',
            field=models.SmallIntegerField(choices=[(0, 'Motor'), (1, 'Bearing'), (2, 'Rotor'), (3, 'Stator')], default=0, verbose_name='Equipment type'),
        ),
        migrations.AddField(
            model_name='rotor',
            name='equip_type',
            field=models.SmallIntegerField(choices=[(0, 'Motor'), (1, 'Bearing'), (2, 'Rotor'), (3, 'Stator')], default=2, verbose_name='Equipment type'),
        ),
        migrations.AddField(
            model_name='stator',
            name='equip_type',
            field=models.SmallIntegerField(choices=[(0, 'Motor'), (1, 'Bearing'), (2, 'Rotor'), (3, 'Stator')], default=3, verbose_name='Equipment type'),
        ),
    ]
