# Generated by Django 2.1 on 2019-03-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0011_auto_20190326_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentsignalpack',
            name='rpm',
            field=models.SmallIntegerField(default=3000, verbose_name='RPM'),
        ),
    ]
